/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoleSelectRouteImport } from './routes/role-select'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentorLoginRouteImport } from './routes/mentor-login'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as MeRouteImport } from './routes/me'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as CoachLoginRouteImport } from './routes/coach-login'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PracticeMoodRouteImport } from './routes/practice.mood'
import { Route as PracticeMeditateRouteImport } from './routes/practice.meditate'
import { Route as PracticeJournalRouteImport } from './routes/practice.journal'
import { Route as PracticeBreatheRouteImport } from './routes/practice.breathe'
import { Route as PracticeAffirmRouteImport } from './routes/practice.affirm'
import { Route as AdminWellnessRouteImport } from './routes/admin.wellness'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAgentRouteImport } from './routes/admin.agent'
import { Route as ApiPublicSeedTestRouteImport } from './routes/api/public/seed-test'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectRoute = RoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorLoginRoute = MentorLoginRouteImport.update({
  id: '/mentor-login',
  path: '/mentor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachLoginRoute = CoachLoginRouteImport.update({
  id: '/coach-login',
  path: '/coach-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PracticeMoodRoute = PracticeMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeMeditateRoute = PracticeMeditateRouteImport.update({
  id: '/meditate',
  path: '/meditate',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeJournalRoute = PracticeJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeBreatheRoute = PracticeBreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeAffirmRoute = PracticeAffirmRouteImport.update({
  id: '/affirm',
  path: '/affirm',
  getParentRoute: () => PracticeRoute,
} as any)
const AdminWellnessRoute = AdminWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentRoute = AdminAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSeedTestRoute = ApiPublicSeedTestRouteImport.update({
  id: '/api/public/seed-test',
  path: '/api/public/seed-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/coach-login': typeof CoachLoginRoute
  '/focus': typeof FocusRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/me': typeof MeRoute
  '/mentor': typeof MentorRoute
  '/mentor-login': typeof MentorLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/portals': typeof PortalsRoute
  '/practice': typeof PracticeRouteWithChildren
  '/role-select': typeof RoleSelectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/practice/affirm': typeof PracticeAffirmRoute
  '/practice/breathe': typeof PracticeBreatheRoute
  '/practice/journal': typeof PracticeJournalRoute
  '/practice/meditate': typeof PracticeMeditateRoute
  '/practice/mood': typeof PracticeMoodRoute
  '/admin/': typeof AdminIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/api/public/seed-test': typeof ApiPublicSeedTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/coach-login': typeof CoachLoginRoute
  '/focus': typeof FocusRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/me': typeof MeRoute
  '/mentor': typeof MentorRoute
  '/mentor-login': typeof MentorLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/portals': typeof PortalsRoute
  '/role-select': typeof RoleSelectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/practice/affirm': typeof PracticeAffirmRoute
  '/practice/breathe': typeof PracticeBreatheRoute
  '/practice/journal': typeof PracticeJournalRoute
  '/practice/meditate': typeof PracticeMeditateRoute
  '/practice/mood': typeof PracticeMoodRoute
  '/admin': typeof AdminIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/api/public/seed-test': typeof ApiPublicSeedTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/coach-login': typeof CoachLoginRoute
  '/focus': typeof FocusRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/me': typeof MeRoute
  '/mentor': typeof MentorRoute
  '/mentor-login': typeof MentorLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/portals': typeof PortalsRoute
  '/practice': typeof PracticeRouteWithChildren
  '/role-select': typeof RoleSelectRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/wellness': typeof AdminWellnessRoute
  '/practice/affirm': typeof PracticeAffirmRoute
  '/practice/breathe': typeof PracticeBreatheRoute
  '/practice/journal': typeof PracticeJournalRoute
  '/practice/meditate': typeof PracticeMeditateRoute
  '/practice/mood': typeof PracticeMoodRoute
  '/admin/': typeof AdminIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/api/public/seed-test': typeof ApiPublicSeedTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/coach'
    | '/coach-login'
    | '/focus'
    | '/home'
    | '/learn'
    | '/me'
    | '/mentor'
    | '/mentor-login'
    | '/onboarding'
    | '/plan'
    | '/portals'
    | '/practice'
    | '/role-select'
    | '/sitemap.xml'
    | '/admin/agent'
    | '/admin/announcements'
    | '/admin/content'
    | '/admin/people'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/wellness'
    | '/practice/affirm'
    | '/practice/breathe'
    | '/practice/journal'
    | '/practice/meditate'
    | '/practice/mood'
    | '/admin/'
    | '/practice/'
    | '/api/public/seed-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/coach'
    | '/coach-login'
    | '/focus'
    | '/home'
    | '/learn'
    | '/me'
    | '/mentor'
    | '/mentor-login'
    | '/onboarding'
    | '/plan'
    | '/portals'
    | '/role-select'
    | '/sitemap.xml'
    | '/admin/agent'
    | '/admin/announcements'
    | '/admin/content'
    | '/admin/people'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/wellness'
    | '/practice/affirm'
    | '/practice/breathe'
    | '/practice/journal'
    | '/practice/meditate'
    | '/practice/mood'
    | '/admin'
    | '/practice'
    | '/api/public/seed-test'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/auth'
    | '/coach'
    | '/coach-login'
    | '/focus'
    | '/home'
    | '/learn'
    | '/me'
    | '/mentor'
    | '/mentor-login'
    | '/onboarding'
    | '/plan'
    | '/portals'
    | '/practice'
    | '/role-select'
    | '/sitemap.xml'
    | '/admin/agent'
    | '/admin/announcements'
    | '/admin/content'
    | '/admin/people'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/wellness'
    | '/practice/affirm'
    | '/practice/breathe'
    | '/practice/journal'
    | '/practice/meditate'
    | '/practice/mood'
    | '/admin/'
    | '/practice/'
    | '/api/public/seed-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  CoachLoginRoute: typeof CoachLoginRoute
  FocusRoute: typeof FocusRoute
  HomeRoute: typeof HomeRoute
  LearnRoute: typeof LearnRoute
  MeRoute: typeof MeRoute
  MentorRoute: typeof MentorRoute
  MentorLoginRoute: typeof MentorLoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  PortalsRoute: typeof PortalsRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  RoleSelectRoute: typeof RoleSelectRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicSeedTestRoute: typeof ApiPublicSeedTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-select': {
      id: '/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof RoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-login': {
      id: '/mentor-login'
      path: '/mentor-login'
      fullPath: '/mentor-login'
      preLoaderRoute: typeof MentorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-login': {
      id: '/coach-login'
      path: '/coach-login'
      fullPath: '/coach-login'
      preLoaderRoute: typeof CoachLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/practice/mood': {
      id: '/practice/mood'
      path: '/mood'
      fullPath: '/practice/mood'
      preLoaderRoute: typeof PracticeMoodRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/meditate': {
      id: '/practice/meditate'
      path: '/meditate'
      fullPath: '/practice/meditate'
      preLoaderRoute: typeof PracticeMeditateRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/journal': {
      id: '/practice/journal'
      path: '/journal'
      fullPath: '/practice/journal'
      preLoaderRoute: typeof PracticeJournalRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/breathe': {
      id: '/practice/breathe'
      path: '/breathe'
      fullPath: '/practice/breathe'
      preLoaderRoute: typeof PracticeBreatheRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/affirm': {
      id: '/practice/affirm'
      path: '/affirm'
      fullPath: '/practice/affirm'
      preLoaderRoute: typeof PracticeAffirmRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/admin/wellness': {
      id: '/admin/wellness'
      path: '/wellness'
      fullPath: '/admin/wellness'
      preLoaderRoute: typeof AdminWellnessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent': {
      id: '/admin/agent'
      path: '/agent'
      fullPath: '/admin/agent'
      preLoaderRoute: typeof AdminAgentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/seed-test': {
      id: '/api/public/seed-test'
      path: '/api/public/seed-test'
      fullPath: '/api/public/seed-test'
      preLoaderRoute: typeof ApiPublicSeedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgentRoute: typeof AdminAgentRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminWellnessRoute: typeof AdminWellnessRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentRoute: AdminAgentRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminWellnessRoute: AdminWellnessRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PracticeRouteChildren {
  PracticeAffirmRoute: typeof PracticeAffirmRoute
  PracticeBreatheRoute: typeof PracticeBreatheRoute
  PracticeJournalRoute: typeof PracticeJournalRoute
  PracticeMeditateRoute: typeof PracticeMeditateRoute
  PracticeMoodRoute: typeof PracticeMoodRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeAffirmRoute: PracticeAffirmRoute,
  PracticeBreatheRoute: PracticeBreatheRoute,
  PracticeJournalRoute: PracticeJournalRoute,
  PracticeMeditateRoute: PracticeMeditateRoute,
  PracticeMoodRoute: PracticeMoodRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  CoachLoginRoute: CoachLoginRoute,
  FocusRoute: FocusRoute,
  HomeRoute: HomeRoute,
  LearnRoute: LearnRoute,
  MeRoute: MeRoute,
  MentorRoute: MentorRoute,
  MentorLoginRoute: MentorLoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  PortalsRoute: PortalsRoute,
  PracticeRoute: PracticeRouteWithChildren,
  RoleSelectRoute: RoleSelectRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicSeedTestRoute: ApiPublicSeedTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
